# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'french-ml-reading-group'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-204831507-3'

menu:
- {name: 'About',   url: 'about.html'}
- {name: 'Blog', url: 'blog.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'envelope',   link: 'mailto:sonnery.hugo@mila.quebec'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer posts'
  previous_page: 'Older posts'

sharing_button_prompt: 'Feel free to share !'

related_posts: 'You may also enjoy :'

post_date_prefix: 'Written on'
